version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on: 
      - db
  db:
    image: postgres:11
    environment: 
      - 'POSTGRES_HOST_AUTH_METHOD=trust'